# This file documents repositories that are nurtured by Ansible DevTools team.
# Not all these repos are fully managed or maintained by the team.
# We aim to use this file when performing maintenance and audit.
#
# Symlink this as ~/pre.yml and use https://github.com/pycontribs/gh-pre
# to review open pull requests and issues.
repos:
  # primary projects
  - ansible/ansible-compat
  - ansible/ansible-creator # scaffolding (templating) for new content
  - ansible/ansible-dev-tools # former cdk/sdk, the devtools 'bundle', server
  - ansible/ansible-development-environment # former pip4a (venv installer)
  - ansible/ansible-lint
  - ansible/ansible-navigator
  - ansible/community-ansible-dev-tools-image
  - ansible/creator-ee # deprecated in favour of community-ansible-dev-tools-image
  - ansible/molecule
  - ansible/pytest-ansible
  - ansible/team-devtools
  - ansible/tox-ansible
  - ansible/vscode-ansible

  # experimental / tech-preview
  - ansible/ansible-backstage-plugins # private

  # auxiliary (usually dependencies)
  - ansible-collections/community.molecule
  - ansible/ansible-workspace-env-reference-image # dev-spaces reference
  - ansible/mkdocs-ansible
  - ansible/team-devtools
  - pycontribs/enrich
  - pycontribs/subprocess-tee

  # nurtured (helped on best effort basis)
  - ansible-community/molecule-plugins

  # unmaintained, obsoleted or archived:
  # - ansible-community/protogen # deprecated?
  # - ansible-community/role2collection
  # - ansible/ansible-language-server (now part vscode-ansible)
  # - ansible/ansible-lint-action (now part of ansible-lint)
  # - pycontribs/selinux
  # - pytest-molecule
