# This file documents repositories that are nurtured by Ansible DevTools team.
# Not all these repos are fully managed or maintained by the team.
# We aim to use this file when performing maintenance and audit.
repos:
  - ansible-community/molecule
  - ansible-community/molecule-plugins
  - ansible-community/protogen  # deprecated?
  - ansible-community/role2collection
  - ansible-community/sphinx_ansible_theme
  - ansible/ansible-compat
  - ansible/ansible-language-server
  - ansible/ansible-lint
  - ansible/ansible-lint-action
  - ansible/ansible-navigator
  - ansible/creator-ee
  - ansible/devtools
  - ansible/vscode-ansible
  - pycontribs/enrich
  - pycontribs/selinux
  - pycontribs/subprocess-tee
