# push workflow is shared and expected to perform actions after a merge happens
# on a maintenance branch (default or release). For example updating the
# draft release-notes.
name: push

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      - 'releases/**'
      - 'stable/**'
  workflow_call:  # allows reuse of this workflow from other devtools repos
    secrets:
      GITHUB_TOKEN:
        description: 'Github token needed for access to release drafts'
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
