---
name: tox-check

on:
  workflow_call:
    inputs:
      jobs_producing_coverage:
        default: 5
        description: Number of jobs producing coverage.xml files
        required: false
        type: number
      tests_outcome:
        description: The needs context from the tests
        required: true
        type: string

jobs:
  check:
    if: always()
    permissions:
      pull-requests: write # allow codenotify to comment on pull-request
      id-token: write
      checks: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip3 install 'coverage>=7.5.1'

      - name: Merge logs into a single archive
        uses: actions/upload-artifact/merge@v4
        with:
          name: logs.zip
          pattern: logs-*.zip
          separate-directories: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: logs.zip

      - name: Check for expected number of coverage.xml reports
        env:
          JOBS_PRODUCING_COVERAGE: ${{ inputs.jobs_producing_coverage }}
        run: |
          if [ "$(find . -name coverage.xml | wc -l | bc)" -ne "${JOBS_PRODUCING_COVERAGE}" ]; then
            echo "::error::Number of coverage.xml files was not the expected one (${JOBS_PRODUCING_COVERAGE}): $(find . -name coverage.xml |xargs echo)"
            exit 1
          fi

      - name: Upload coverage data
        uses: codecov/codecov-action@v4
        with:
          name: ${{ matrix.passed_name }}
          fail_ci_if_error: true
          use_oidc: true

      - name: Check codecov.io status
        if: github.event_name == 'pull_request'
        uses: coactions/codecov-status@main

      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ inputs.tests_outcome }}

      - name: Delete Merged Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true

      - name: Notify repository owners about changes affecting them
        uses: sourcegraph/codenotify@v0.6.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/sourcegraph/codenotify/issues/19
        continue-on-error: true
